apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitpoll-pv-claim
  namespace: bitpoll-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
