apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitpoll-pv
  namespace: bitpoll-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/bitpoll/database"
