apiVersion: v1
kind: Service
metadata:
  name: bitpoll-service
  namespace: bitpoll-ns
spec:
  selector:
    app: bitpoll
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
